apiVersion: apps/v1
kind: Deployment
metadata:
  name: apacheds-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apacheds
  template:
    metadata:
      labels:
        app: apacheds
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: apacheds
        image: apacheds.azurecr.io/myapacheds:am25
        ports:
        - containerPort: 10389
        - containerPort: 10636