apiVersion: v1
kind: Service
metadata:
  name: apacheds-service
spec:
  selector:
    app: apacheds
  ports:
  - protocol: TCP
    port: 10389
    targetPort: 10389
    name: ldap-port
  - protocol: TCP
    port: 10636
    targetPort: 10636
    name: ldaps-port
  type: LoadBalancer
